export const WeatherDescKo = [
  { id: 201, desc: "가벼운 비를 동반한 천둥구름", icon: "lightning" },
  { id: 200, desc: "비를 동반한 천둥구름", icon: "lightning" },
  { id: 202, desc: "폭우를 동반한 천둥구름", icon: "lightning" },
  { id: 210, desc: "약한 천둥구름", icon: "lightning" },
  { id: 211, desc: "천둥구름", icon: "lightning" },
  { id: 212, desc: "강한 천둥구름", icon: "lightning" },
  { id: 221, desc: "불규칙적 천둥구름", icon: "lightning" },
  { id: 230, desc: "약한 연무를 동반한 천둥구름", icon: "lightning" },
  { id: 231, desc: "연무를 동반한 천둥구름", icon: "lightning" },
  { id: 232, desc: "강한 안개비를 동반한 천둥구름", icon: "lightning" },
  { id: 300, desc: "가벼운 안개비", icon: "rain" },
  { id: 301, desc: "안개비", icon: "rain" },
  { id: 302, desc: "강한 안개비", icon: "rain" },
  { id: 310, desc: "가벼운 적은비", icon: "rain" },
  { id: 311, desc: "적은비", icon: "rain" },
  { id: 312, desc: "강한 적은비", icon: "rain" },
  { id: 313, desc: "소나기와 안개비", icon: "rain" },
  { id: 314, desc: "강한 소나기와 안개비", icon: "rain" },
  { id: 321, desc: "소나기", icon: "rain" },
  { id: 500, desc: "약한 비", icon: "rain" },
  { id: 501, desc: "중간 비", icon: "rain" },
  { id: 771, desc: "돌풍", icon: "hurricane" },
  { id: 781, desc: "토네이도", icon: "hurricane" },
  { id: 800, desc: "맑은 하늘", icon: "day-sunny" },
  { id: 801, desc: "약간의 구름이 낀 하늘", icon: "cloudy" },
  { id: 802, desc: "드문드문 구름이 낀 하늘", icon: "cloudy-gusts" },
  { id: 803, desc: "구름이 거의 없는 하늘", icon: "day-cloudy" },
  { id: 804, desc: "구름으로 뒤덮인 흐린 하늘", icon: "cloudy" },
  { id: 900, desc: "토네이도", icon: "hurricane" },
  { id: 901, desc: "태풍", icon: "hurricane" },
  { id: 902, desc: "허리케인", icon: "hurricane" },
  { id: 903, desc: "한랭", icon: "wind" },
  { id: 904, desc: "고온", icon: "day-sunny" },
  { id: 905, desc: "바람부는", icon: "wind" },
  { id: 906, desc: "우박", icon: "hail" },
  { id: 951, desc: "바람이 거의 없는", icon: "day-sunny" },
  { id: 952, desc: "약한 바람", icon: "wind" },
  { id: 953, desc: "부드러운 바람", icon: "wind" },
  { id: 954, desc: "중간 세기 바람", icon: "wind" },
  { id: 955, desc: "신선한 바람", icon: "wind" },
  { id: 956, desc: "센 바람", icon: "wind" },
  { id: 957, desc: "돌풍에 가까운 센 바람", icon: "wind" },
  { id: 958, desc: "돌풍", icon: "wind" },
  { id: 959, desc: "심각한 돌풍", icon: "wind" },
  { id: 960, desc: "폭풍", icon: "hurricane" },
  { id: 961, desc: "강한 폭풍", icon: "hurricane" },
  { id: 962, desc: "허리케인", icon: "hurricane" }
];